import { readFileSync, existsSync } from "node:fs";
import { isAbsolute, resolve as resolvePath } from "node:path";
import os from "node:os";
import { parseHuJson } from "../hujson.js";
import type {
  ServiceConfig,
  ServiceLogConfig,
  ServiceRestartPolicy,
} from "./types.js";

const NAME_RE = /^[a-zA-Z0-9-]+$/;

const SECRET_VALUE_RE =
  /tskey-|secret|token|password|passwd|api[_-]?key|credential/i;

const DEFAULT_RESTART: ServiceRestartPolicy = {
  onFailure: true,
  delaySeconds: 5,
  maxRetries: 10,
};

export function generateSampleConfig(
  name: string,
  description = "Tailscale TCP Relay Service - managed by tailsacle-cli",
): string {
  return `// .tailsacle-service.jsonc — generated by: tailsacle-cli service init
{
  // Tên service (phải là slug, ký tự alphanumeric và dấu gạch nối)
  "name": "${name}",

  // Mô tả hiển thị trong SCM / systemd
  "description": "${description}",

  // Người dùng chạy service: "current" = user đang chạy lệnh install
  // Windows: "LocalSystem" hoặc ".\\username"  |  Linux: "username"
  "user": "current",

  // Thư mục làm việc (mặc định: thư mục chứa file config này)
  "workingDir": ".",

  // Node.js entrypoint — để trống để dùng tailsacle-cli binary tự động
  "script": "",

  // Arguments truyền vào script
  "args": ["relay", "--listen", "18888", "--target", "127.0.0.1:19999"],

  // Biến môi trường (secrets sẽ được mask trong log)
  "env": {
    "NODE_ENV": "production"
  },

  // Chính sách restart
  "restart": {
    "onFailure": true,
    "delaySeconds": 5,
    "maxRetries": 10
  },

  // Log settings (chỉ áp dụng Windows — Linux dùng journald tự động)
  "log": {
    "dir": "./logs",
    "maxSizeMb": 10,
    "keepFiles": 5
  }
}
`;
}

export function loadServiceConfig(filePath: string): ServiceConfig {
  if (!existsSync(filePath)) {
    throw new Error(
      `SERVICE_CONFIG_NOT_FOUND: config file not found at ${filePath}`,
    );
  }
  const raw = readFileSync(filePath, "utf8");
  let parsed: unknown;
  try {
    parsed = parseHuJson(raw);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(
      `SERVICE_CONFIG_INVALID: config file is not valid JSON/JSONC: ${detail}`,
    );
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error(
      "SERVICE_CONFIG_INVALID: config root must be a JSON object",
    );
  }
  const baseDir = resolvePath(
    process.cwd(),
    filePath.split(/[\\/]/).slice(0, -1).join("/") || ".",
  );
  return validateServiceConfig(parsed as Record<string, unknown>, baseDir);
}

export function validateServiceConfig(
  input: Record<string, unknown>,
  baseDir: string,
): ServiceConfig {
  const name = input.name;
  if (typeof name !== "string" || !name.trim()) {
    throw new Error("SERVICE_CONFIG_MISSING_FIELD: name");
  }
  if (!NAME_RE.test(name)) {
    throw new Error(
      `SERVICE_NAME_INVALID: only alphanumeric and hyphens allowed, got "${name}"`,
    );
  }
  const description =
    typeof input.description === "string" && input.description.trim()
      ? input.description.trim()
      : "Tailscale TCP Relay Service - managed by tailsacle-cli";
  const user =
    typeof input.user === "string" && input.user.trim()
      ? input.user.trim()
      : "current";
  const workingDirRaw =
    typeof input.workingDir === "string" && input.workingDir.trim()
      ? input.workingDir.trim()
      : ".";
  const workingDir = isAbsolute(workingDirRaw)
    ? workingDirRaw
    : resolvePath(baseDir, workingDirRaw);
  if (!existsSync(workingDir)) {
    throw new Error(
      `SERVICE_WORKDIR_NOT_FOUND: workingDir does not exist: ${workingDir}`,
    );
  }
  let script: string | undefined;
  if (typeof input.script === "string" && input.script.trim()) {
    script = isAbsolute(input.script)
      ? input.script
      : resolvePath(baseDir, input.script);
    if (!existsSync(script)) {
      throw new Error(
        `SERVICE_SCRIPT_NOT_FOUND: script does not exist: ${script}`,
      );
    }
  }
  if (
    !Array.isArray(input.args) ||
    !input.args.every((a) => typeof a === "string")
  ) {
    throw new Error("SERVICE_CONFIG_MISSING_FIELD: args");
  }
  const args = (input.args as string[]).map((a) => a.trim()).filter(Boolean);
  const envInput =
    typeof input.env === "object" &&
    input.env !== null &&
    !Array.isArray(input.env)
      ? (input.env as Record<string, unknown>)
      : {};
  const env: Record<string, string> = {};
  for (const [key, value] of Object.entries(envInput)) {
    if (typeof value === "string") env[key] = value;
  }
  const restartInput =
    typeof input.restart === "object" && input.restart !== null
      ? (input.restart as Record<string, unknown>)
      : {};
  const restart: ServiceRestartPolicy = {
    onFailure:
      typeof restartInput.onFailure === "boolean"
        ? restartInput.onFailure
        : DEFAULT_RESTART.onFailure,
    delaySeconds:
      typeof restartInput.delaySeconds === "number" &&
      restartInput.delaySeconds >= 0
        ? Math.floor(restartInput.delaySeconds)
        : DEFAULT_RESTART.delaySeconds,
    maxRetries:
      typeof restartInput.maxRetries === "number" &&
      restartInput.maxRetries >= 0
        ? Math.floor(restartInput.maxRetries)
        : DEFAULT_RESTART.maxRetries,
  };
  let log: ServiceLogConfig | undefined;
  if (typeof input.log === "object" && input.log !== null) {
    const logInput = input.log as Record<string, unknown>;
    const logDirRaw =
      typeof logInput.dir === "string" && logInput.dir.trim()
        ? logInput.dir
        : "./logs";
    log = {
      dir: isAbsolute(logDirRaw)
        ? logDirRaw
        : resolvePath(workingDir, logDirRaw),
      maxSizeMb:
        typeof logInput.maxSizeMb === "number" && logInput.maxSizeMb > 0
          ? logInput.maxSizeMb
          : 10,
      keepFiles:
        typeof logInput.keepFiles === "number" && logInput.keepFiles > 0
          ? logInput.keepFiles
          : 5,
    };
  }
  return {
    name,
    description,
    user,
    workingDir,
    script,
    args,
    env,
    restart,
    log,
  };
}

export function resolveUserName(user: string): string {
  return user === "current" ? os.userInfo().username : user;
}

export function maskEnv(env: Record<string, string>): Record<string, string> {
  const masked: Record<string, string> = {};
  for (const [key, value] of Object.entries(env)) {
    masked[key] = SECRET_VALUE_RE.test(value) ? "****" : value;
  }
  return masked;
}

export function isSecretValue(value: string): boolean {
  return SECRET_VALUE_RE.test(value);
}
