/**
 * Versioned, machine-readable agent contract. `tools[]` describes every CLI
 * entry point precisely enough for an agent to call it safely without reading
 * the implementation, including the credential it resolves, the scopes and
 * privileges it requires, its side effects, and its exit/error contract.
 */
export const manifest = {
  manifestVersion: 2,
  name: "tailsacle-cli",
  bins: ["tailsacle-cli", "tscli", "tailscale-cli-opencode"],
  envelope: {
    fields: [
      "ok",
      "command",
      "durationMs",
      "resolved",
      "warnings",
      "requiredPrivileges",
      "sideEffects",
      "retryable",
      "error",
    ],
    errorCodes: {
      retryable: 75,
      credential: 3,
      policy: 8,
      binary: 5,
      localTailscale: 6,
      funnelService: 7,
      privilege: 9,
      general: 1,
    },
    errorMap: {
      CREDENTIAL_NOT_FOUND: 3,
      CREDENTIAL_AMBIGUOUS: 3,
      CREDENTIAL_FORMAT_UNSUPPORTED: 3,
      AUTH_KEY_FORMAT_INVALID: 3,
      AUTH_KEY_NOT_CONFIGURED: 3,
      POLICY_FILE_NOT_FOUND: 8,
      POLICY_VERIFY_FAILED: 8,
      POLICY_CONFIRMATION_REQUIRED: 8,
      POLICY_PROVISION_CONFIRMATION_REQUIRED: 8,
      POLICY_HUJSON_MERGE_FAILED: 8,
      TAILSCALE_BINARY_NOT_FOUND: 5,
      BIN_DOWNLOAD_HTTP_400: 5,
      BIN_CHECKSUM_MISMATCH: 5,
      BIN_SHA256_INVALID: 5,
      BIN_EXTRACT_FAILED: 5,
      BIN_INDEX_INCOMPLETE: 5,
      BIN_TRACK_UNSUPPORTED: 5,
      TAILSCALE_NOT_RUNNING: 6,
      FUNNEL_PORT_UNSUPPORTED: 7,
      FUNNEL_TARGET_REQUIRED: 7,
      FUNNEL_TCP_INVALID: 7,
      FUNNEL_ATTR_REQUIRED: 7,
      FUNNEL_EPHEMERAL: 7,
      FUNNEL_DNS_NOT_PUBLISHED: 7,
      FUNNEL_ENDPOINT_UNREACHABLE: 7,
      PRIVILEGE_REQUIRED: 9,
    },
    privilegeMap: {
      TAILSCALE_BINARY_NOT_FOUND:
        "install Tailscale or run as root/Administrator for auto-download",
      TAILSCALE_NOT_RUNNING:
        "start tailscaled (systemctl/enable or run as root/Administrator)",
      BIN_WINDOWS_MANUAL:
        "install the Tailscale MSI as Administrator or set TS_TAILSCALE_BIN",
    },
    warningCodes: [
      "PROVISIONED_TAGS",
      "PROVISIONED_FUNNEL",
      "ENABLED_HTTPS",
      "KEY_EXPIRY_DEFAULT",
      "KEY_EXPIRY_MAX",
      "KEY_EXPIRY_UNLIMITED",
      "KEY_EXPIRY_CLAMPED",
      "AUTO_TAG",
      "REUSABLE_KEY_DEFAULTED",
      "TAILNET_DEFAULTED",
      "TAILNET_DOMAIN_UNUSUAL",
      "NO_TAGS_CONFIGURED",
      "CREDENTIAL_AMBIGUOUS",
      "CREDENTIAL_NOT_FOUND",
      "API_CREDENTIAL_NOT_CONFIGURED",
      "SIDE_EFFECT_PLAN",
      "FUNNEL_TARGET_DEFAULTED",
      "CLEANUP_SKIPPED",
      "CONFIG_FILE_LOADED",
    ],
  },
  resolve_credentials: {
    precedence: [
      "TS_AUTH_KEY",
      "TS_CREDENTIAL_ENV-selected env var (or --credential-env)",
      "TS_CLIENT_SECRET",
      "OAuth trust credential in any tskey-client- env var",
      "TS_OAUTH_CLIENT_ID + TS_OAUTH_CLIENT_SECRET",
      "TS_ACCESS_TOKEN",
      "TS_API_KEY",
    ],
    override:
      "--credential-env <name> (or TS_CREDENTIAL_ENV / config file credentialEnv) to select one specific env var holding the trust credential (required when detection is ambiguous); --client-secret/--client-id override TS_CLIENT_SECRET/TS_CLIENT_ID for one run (visible in process listings)",
    auto_detect: {
      source: "any env var whose value starts with tskey-client-",
    },
  },
  tools: [
    {
      name: "doctor",
      summary:
        "Resolve credentials, runtime, local binary and API capability with no remote side effects.",
      command: ["doctor", ["--detect-credentials"], ["--show-resolution"]],
      consumes: {
        inputs: [
          "env.tskey-client-*",
          "env.TS_API_KEY",
          "env.TS_ACCESS_TOKEN",
          "env.TS_OAUTH_*",
        ],
        inputsSchema: "no positional args; flags optional",
      },
      outputs: {
        json: "CommandResult(envelope) > resolved { config, credential {found,source,masked}, apiCredential, binary, runtime }",
      },
      scopes: ["none (local only)"],
      privileges: ["read files", "read env"],
      sideEffects: ["none"],
      retryable: false,
      confirmation: "never",
    },
    {
      name: "deploy",
      summary:
        "Join the tailnet with auth-key or resolved credential, optionally configure Serve/Funnel, and auto-cleanup matching offline devices.",
      command: [
        "deploy",
        "--yes",
        ["--dry-run"],
        ["--expose <target...>"],
        ["--funnel"],
        ["--apply-policy"],
        ["--enable-https"],
        ["--cleanup"],
        ["--bin <path>"],
        ["--ssh | --no-ssh"],
        ["--state-dir <path>"],
        ["--backup-dir <path>"],
      ],
      consumes: {
        inputs: [
          "TS_AUTH_KEY or API credential",
          "TS_TAGS",
          "TS_HOSTNAME",
          "TS_PROFILE",
          "TS_EPHEMERAL",
          "TS_KEY_EXPIRY",
        ],
        inputsSchema: 'env-driven; --expose targets "PORT#path=target"',
      },
      outputs: {
        json: "resolved { binary, device, authKeySource, exposures, warnings, cleanup? }",
      },
      scopes: [
        "auth_keys",
        "devices:core:read",
        "devices:core:write",
        "policy_file (provisioning)",
        "all (HTTPS enable)",
      ],
      privileges: [
        "tailscaled needs root/admin unless userspace is pre-configured",
      ],
      sideEffects: [
        "authenticate node",
        "write Tailscale state",
        "create auth-key",
        "configure Serve/Funnel",
        "provision tailnet policy (--apply-policy)",
        "enable tailnet HTTPS (--enable-https)",
        "delete offline devices (--cleanup)",
      ],
      retryable: true,
      confirmation: "--yes or TTY for every provisioning/cleanup side effect",
    },
    {
      name: "up",
      summary: "Deploy alias without exposure configuration.",
      command: [
        "up",
        ["--dry-run"],
        ["--yes"],
        ["--apply-policy"],
        ["--cleanup"],
        ["--ssh | --no-ssh"],
        ["--state-dir <path>"],
        ["--backup-dir <path>"],
      ],
      consumes: {
        inputs: ["same as deploy", "TS_NO_CLEANUP=1 disables auto-cleanup"],
      },
      outputs: { json: "same as deploy" },
      scopes: ["auth_keys", "devices:core:*"],
      privileges: [
        "tailscaled needs root/admin unless userspace is pre-configured",
      ],
      sideEffects: [
        "authenticate node",
        "write Tailscale state",
        "create auth-key",
        "delete offline devices (--cleanup)",
      ],
      retryable: true,
      confirmation: "--yes or TTY",
    },
    {
      name: "funnel",
      summary:
        "Expose a local service publicly via Tailscale Funnel and verify public DNS propagation plus the live TLS/TCP endpoint.",
      command: [
        "funnel",
        "[target]",
        ["--https <port>"],
        ["--tcp <public:local>"],
        ["--path <path>"],
        ["--expose <port[/path]=local>..."],
        ["--yes"],
        ["--apply-policy"],
        ["--enable-https"],
        ["--verify-timeout <sec>"],
        ["--ssh | --no-ssh"],
        ["--state-dir <path>"],
      ],
      consumes: {
        inputs: [
          "target or $PORT",
          "config tags (funnel node attribute)",
          "HTTPS enablement",
        ],
      },
      outputs: {
        json: "resolved { target, public, https, path, url?, dnsPropagated, dnsAttempts, verified, tlsVerified?, tlsVerifiedPorts?, tcpVerified?, verifyAttempts }",
      },
      scopes: ["policy_file (provisioning)", "all (HTTPS enable)"],
      privileges: [
        "tailscaled running",
        "funnel node attribute or --apply-policy",
        "non-ephemeral node",
      ],
      sideEffects: [
        "configure Funnel config",
        "provision nodeAttrs (--apply-policy)",
        "enable tailnet HTTPS (--enable-https)",
      ],
      retryable: true,
      confirmation:
        "--yes or TTY for provisioning; DNS and live-endpoint verification retry up to --verify-timeout",
    },
    {
      name: "serve",
      summary: "Share a local service on the tailnet (not public).",
      command: [
        "serve",
        "<target>",
        ["--https <port>"],
        ["--http <port>"],
        ["--tcp <port>"],
        ["--path <path>"],
      ],
      consumes: { inputs: ["target"] },
      outputs: { json: "resolved { target, public, path, https? }" },
      scopes: ["none"],
      privileges: ["tailscaled running"],
      sideEffects: ["configure Serve config"],
      retryable: false,
      confirmation: "never",
    },
    {
      name: "relay",
      summary:
        "Run a TCP relay proxy to forward connections to another machine (single or multi-port, or via config file), optionally exposing via Serve/Funnel.",
      command: [
        "relay",
        ["-l, --listen <port>"],
        ["-t, --target <host:port>"],
        ["-m, --map <mapping...>"],
        ["-f, --file <configPath>"],
        ["--host <address>"],
        ["--target-host <address>"],
        ["--serve"],
        ["--funnel"],
      ],
      consumes: {
        inputs: ["listen/target port", "mapping array", "JSON config file"],
      },
      outputs: {
        json: "resolved { status, count, mappings, tailscaleServe, tailscaleFunnel }",
      },
      scopes: ["none"],
      privileges: ["none (or tailscaled running if --serve/--funnel)"],
      sideEffects: ["run local TCP proxy", "optional Serve/Funnel configure"],
      retryable: true,
      confirmation: "never",
    },
    {
      name: "relay-mcp-postgres",
      summary:
        "Run TCP relays to PostgreSQL and serve a nexql-mcp HTTP MCP endpoint exposing all databases on the relayed instance (agent-driven connection via setup_connection).",
      command: [
        "relay-mcp-postgres",
        ["-l, --listen <port>"],
        ["-t, --target <host:port>"],
        ["-m, --map <mapping...>"],
        ["-f, --file <configPath>"],
        ["--host <address>"],
        ["--target-host <address>"],
        ["--mcp-port <port>"],
        ["--token <token>"],
        ["--user <user>"],
        ["--password <password>"],
        ["--database <database>"],
        ["--db-retry-interval <ms>"],
        ["--mcp-ready-timeout <ms>"],
        ["--log <path>"],
        ["--serve"],
        ["--funnel"],
      ],
      consumes: {
        inputs: [
          "listen/target port",
          "mapping array",
          "JSON config file",
          "PostgreSQL user/password/database (password via --password or PGPASSWORD/TS_PGPASSWORD env)",
        ],
      },
      outputs: {
        json: "resolved { status, relayCount, mappings, primaryDatabase, mcpHttpUrl, mcpToken, connectionString (masked), nexqlMcpPid, runnerVersion, tailscaleServe, tailscaleFunnel }",
      },
      scopes: ["none"],
      privileges: ["none (or tailscaled running if --serve/--funnel)"],
      sideEffects: [
        "run local TCP proxy",
        "spawn nexql-mcp HTTP MCP server (supervisor respawns until the DB is reachable)",
        "optional Serve/Funnel configure",
      ],
      retryable: true,
      confirmation: "never",
    },
    {
      name: "dns",
      summary: "Read tailnet DNS settings; optionally enable MagicDNS.",
      command: ["dns", ["--enable-magicdns"], ["--dry-run"], ["--yes"]],
      consumes: { inputs: ["API credential"] },
      outputs: {
        json: "resolved { nameservers, preferences, searchpaths } or { magicDNSEnabled: true, dryRun?: boolean }",
      },
      scopes: ["dns:read", "dns (MagicDNS enable)"],
      privileges: ["tailnet admin for DNS writes"],
      sideEffects: ["enable MagicDNS (--enable-magicdns, confirmation)"],
      retryable: false,
      confirmation: "--yes or TTY for --enable-magicdns",
    },
    {
      name: "policy",
      summary:
        "Diff, validate and guarded-sync a HuJSON policy file; use policy-sync for writes.",
      command: [
        "policy",
        ["--file <path>"],
        ["--dry-run"],
        ["--sync"],
        ["--yes"],
        ["--backup-dir <path>"],
      ],
      consumes: { inputs: ["TS_POLICY_FILE or --file path"] },
      outputs: {
        json: "resolved { changed, validated, written, etag?, backup?, diff }",
      },
      scopes: ["policy_file:read", "policy_file"],
      privileges: ["tailnet admin for policy writes"],
      sideEffects: ["policy write + local backup (--sync + confirmation)"],
      retryable: false,
      confirmation: "--yes or TTY before writing",
    },
    {
      name: "status",
      summary: "Show local Tailscale status.",
      command: ["status", ["--show-resolution"]],
      consumes: { inputs: [] },
      outputs: {
        json: "resolved = tailscale status JSON (optionally with credential resolution)",
      },
      scopes: ["none"],
      privileges: ["tailscaled running"],
      sideEffects: ["none"],
      retryable: false,
      confirmation: "never",
    },
    {
      name: "cleanup",
      summary:
        "Find and safely remove matching offline devices (exact hostname/tag match).",
      command: ["cleanup", ["--dry-run"], ["--yes"]],
      consumes: {
        inputs: [
          "TS_CLEANUP_OFFLINE_AFTER seconds",
          "TS_PROTECTED_DEVICES comma list",
        ],
      },
      outputs: {
        json: "resolved { candidates: [{ id, hostname, name, dnsName, tags, lastSeen, offlineSinceSeconds }], deleted: string[] }",
      },
      scopes: ["devices:core:read", "devices:core:write"],
      privileges: ["tailnet admin"],
      sideEffects: ["delete offline devices (--yes/confirmation)"],
      retryable: false,
      confirmation: "--yes or TTY",
    },
    {
      name: "update-bin",
      summary:
        "Download the latest stable Tailscale build into the package cache (never overwrites package-managed binaries) or fall back to the native updater on Windows. Also reachable as the global flag --update-bin (e.g. `tailsacle-cli --update-bin`).",
      command: [
        "update-bin",
        ["--force"],
        ["--skip-checksum"],
        ["--track <track>"],
        ["--yes"],
        ["--dry-run"],
      ],
      consumes: {
        inputs: [
          "TS_BIN_DIR cache override",
          "TS_BIN_VERSION optional pinned version",
          "network access to pkgs.tailscale.com",
        ],
      },
      outputs: { json: "resolved { cached, before?, after?, info? }" },
      scopes: ["none"],
      privileges: ["write to the cache directory"],
      sideEffects: ["download + verify + atomic-install stable binary"],
      retryable: true,
      confirmation: "never (explicit command)",
    },
    {
      name: "service",
      summary:
        "Install, manage and remove a relay/script as a background service: systemd (Linux system/user unit), Windows SCM (WinSW via node-windows), or Windows Task Scheduler (--scheduler, no admin).",
      command: [
        "service",
        "<init|install|uninstall|status|logs|start|stop|restart|list>",
        ["init --name <name> --out <file>"],
        ["install --file <config> [--user] [--scheduler] [--yes]"],
        ["uninstall --name <name> [--yes]"],
        ["status --name <name>"],
        ["logs --name <name> [--lines <n>] [--follow]"],
        ["start|stop|restart --name <name>"],
        ["list"],
      ],
      consumes: {
        inputs: [
          "service config file (.tailsacle-service.jsonc, JSONC supported)",
          "node-windows (optional, Windows SCM path only)",
        ],
      },
      outputs: {
        json: "resolved per subcommand: init { file, name }; install { installed, name, platform, scope, unitPath, status, pid, portsListening }; status { name, status, pid?, uptimeSeconds?, restartCount? }; list ServiceInfo[]",
      },
      scopes: ["none"],
      privileges: [
        "root/sudo for Linux system units (--user avoids sudo)",
        "Administrator for Windows SCM (--scheduler avoids admin)",
      ],
      sideEffects: [
        "write systemd unit or Windows service/task definition",
        "enable and start the service",
        "remove service definition on uninstall",
      ],
      retryable: false,
      confirmation: "--yes or TTY for install/uninstall",
    },
    {
      name: "agent-manifest",
      summary: "Emit this versioned contract.",
      command: ["agent-manifest", ["--json"]],
      consumes: { inputs: [] },
      outputs: { json: "manifest envelope" },
      scopes: ["none"],
      privileges: ["none"],
      sideEffects: ["none"],
      retryable: false,
      confirmation: "never",
    },
    {
      name: "daemon",
      summary: "Inspect or stop the local tailscaled daemon.",
      command: ["daemon", "<status|stop>"],
      consumes: { inputs: [] },
      outputs: { json: "resolved { running, tracked, trackedAlive }" },
      scopes: ["none"],
      privileges: ["none"],
      sideEffects: ["stop tracked userspace tailscaled (stop action)"],
      retryable: false,
      confirmation: "never",
    },
    {
      name: "opencode",
      summary:
        "Separate bin tailscale-cli-opencode: resolve/install opencode (npx -y opencode-ai when missing), grant headless full permissions (permission: allow, the --auto equivalent), start opencode serve in the background, join the tailnet and publish it through a Tailscale Funnel, then verify public DNS + live TLS before printing the public URL. --stop tears the tracked serve and userspace tailscaled down.",
      command: [
        "opencode",
        ["--port <number>"],
        ["--opencode-config <path>"],
        ["--install"],
        ["--no-verify"],
        ["--verify-timeout <seconds>"],
        ["--dry-run"],
        ["--stop"],
        ["--yes"],
        ["--apply-policy"],
        ["--enable-https"],
        ["--state-dir <path>"],
        ["--backup-dir <path>"],
        ["--tag-owner <owner...>"],
        ["--credential-env <name>"],
        ["--profile <profile>"],
        ["--config <path>"],
        ["--json"],
      ],
      consumes: {
        inputs: [
          "env.TS_AUTH_KEY / OAuth trust credential / TS_API_KEY (for join + funnel provisioning)",
          "npx (Node.js 22+) for opencode-ai resolution",
          "network access to npmjs + Tailscale control plane",
        ],
      },
      outputs: {
        json: "resolved { opencode { runner, pid, command, port, configPath, permissionConfig, permissionWritten, permissionExisting, logPath }, deployment, dnsName?, urls[], verified, verifyAttempts? }",
      },
      scopes: ["none (local opencode + tailscale funnel)"],
      privileges: [
        "write ~/.config/opencode and ./opencode.json",
        "npm/npx access for opencode-ai",
        "tailscaled running (userspace auto-started)",
      ],
      sideEffects: [
        "install/resolve opencode-ai via npx (when missing or --install)",
        "start opencode serve (background, tracked in the cache pidfile)",
        "join tailnet and configure Funnel (auto-provision with --apply-policy/--enable-https)",
        "verify public DNS + live TLS endpoint",
      ],
      retryable: false,
      confirmation: "--yes or TTY",
    },
  ],
  policy_writes: {
    flow: [
      "fetch policy + etag",
      "diff/merge (HuJSON-preserving)",
      "validate (POST /acl/validate)",
      "local backup",
      "write with If-Match",
      "verify",
    ],
    hujson:
      "comments and trailing commas preserved for tagOwners/nodeAttrs provisioning; policy command writes the file verbatim",
  },
  cleanup_candidates: {
    schema: {
      id: "string",
      hostname: "string",
      name: "string",
      dnsName: "string",
      tags: "string[]",
      lastSeen: "string?",
      offlineSinceSeconds: "number",
    },
    match:
      "exact normalized hostname (device.hostname/dnsName/name) AND every wanted tag; never substring; devices without lastSeen are never treated as offline",
  },
} as const;
