name: OpenCode Dispatch

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Prompt to send to OpenCode"
        required: true
        type: string
      model:
        description: "Chọn model free"
        required: true
        type: choice
        default: "opencode/big-pickle"
        options:
          - opencode/big-pickle
          - opencode/deepseek-v4-flash-free
          - opencode/mimo-v2.5-free
          - opencode/hy3-free
          - opencode/laguna-s-2.1-free
          - opencode/nemotron-3-ultra-free
          - opencode/nemotron-3.5-lightning-free
      branch:
        description: "Branch to run on"
        required: false
        default: "main"
        type: string

jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 1

      - name: Run OpenCode
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GHCLI_TOKEN_OWNER }}
        with:
          model: ${{ inputs.model }}
          use_github_token: true
          prompt: ${{ inputs.prompt }}
