name: opencode-review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      model:
        description: "Chọn model free"
        required: true
        type: choice
        default: "opencode/big-pickle"
        options:
          - opencode/big-pickle
          - opencode/deepseek-v4-flash-free
          - opencode/mimo-v2.5-free
          - opencode/hy3-free
          - opencode/laguna-s-2.1-free
          - opencode/nemotron-3-ultra-free
          - opencode/nemotron-3.5-lightning-free

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCLI_TOKEN_OWNER: ${{ secrets.GHCLI_TOKEN_OWNER }}
        with:
          model: ${{ inputs.model || 'opencode/big-pickle' }}
          use_github_token: true
          prompt: |
            Review this pull request:
            - Check for code quality issues
            - Look for potential bugs
            - Suggest improvements
            - If you find issues, fix them and commit the changes to this branch
